apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emeland-demo.fullname" . }}-gitsensor-config
  labels:
    {{- include "emeland-demo.labels" . | nindent 4 }}
data:
  sensor.yaml: |
    subscribers:
      - http://{{ include "emeland-demo.fullname" . }}-server:{{ .Values.service.port }}/api/
    watch: true
    repos:
      - type: github
        deployKey: /keys/id_ed25519.pub
        repo: {{ include "emeland-demo.gitRepoSSH" . }}
        branch: {{ .Values.gitsensor.branch }}
        checkoutDir: {{ .Values.gitsensor.checkoutDir }}
        paths:
{{- range .Values.gitsensor.watchedPaths }}
          - {{ . | quote }}
{{- end }}
