{{- if or .Values.gitserver.enabled .Values.gitsensor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emeland-demo.fullname" . }}-deploy-key
  labels:
    {{- include "emeland-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_ed25519: |
    {{- .Values.deployKey.privateKey | nindent 4 }}
  id_ed25519.pub: {{ .Values.deployKey.publicKey | quote }}
  authorized_keys: {{ .Values.deployKey.publicKey | quote }}
{{- end }}
